#!/bin/sh
if [[ `uname` == "Darwin" ]]; then
    SP=" " # Needed for portability with sed
fi
set -e
mkdir -p pb

tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'pfunc-proto')

plref=3.0.0
bkref=release-4.16.1
echo pulling bookkeeper stream proto
mkdir $tmpdir/bk

curl -sL https://github.com/apache/bookkeeper/archive/refs/tags/$bkref.tar.gz | tar xz -C $tmpdir/bk --strip-components=6 bookkeeper-$bkref/stream/proto/src/main/proto
for file in $tmpdir/bk/*.proto; do
    pkg_name=`grep "^package" $file |sed -n 's#package \(.*\);#\1#p'|sed -rn 's#proto\.?##p' | sed 's#\.#\/#g'`
    sed -r -i${SP}'' "s#^option java_package.*#option go_package = \"$pkg_name\";#" $file
done
echo generating bookkeeper libs
protoc --proto_path $tmpdir/bk --go_out=./pb --go-grpc_out=./pb $tmpdir/bk/*.proto

cat <<EOF > ./pb/bookkeeper/doc.go
// Package bookkeeper provides the protocol buffer messages that Bookkeeper
// uses for the stream API.
//
// The protocol definition files are part of the main Bookkeper source,
// located within the Bookkeeper repository at:
// https://github.com/apache/bookkeeper/tree/master/stream/proto/src/main/proto
//
// The generated Go code was created from the source Bookkeeper files at git:
//    tag:      ${bkref}
//
// Files generated by the protoc-gen-go program should not be modified.
package bookkeeper
EOF

echo pulling pulsar funtions proto
mkdir $tmpdir/pulsar
curl -sL https://github.com/apache/pulsar/archive/refs/tags/v$plref.tar.gz | tar xz -C $tmpdir/pulsar --strip-components=6 pulsar-$plref/pulsar-functions/proto/src/main/proto
for file in $tmpdir/pulsar/*.proto; do
    sed -r -i${SP}'' "s#^option java_package.*#option go_package = \"/pulsar/fn\";#" $file
done
echo generating pulsar libs
protoc --proto_path $tmpdir/pulsar --go_out=./pb --go-grpc_out=./pb $tmpdir/pulsar/*.proto

cat <<EOF > ./pb/pulsar/fn/doc.go
// Package fn provides the protocol buffer messages that Pulsar
// uses for the client/broker wire protocol.
// See "Pulsar binary protocol specification" for more information.
// https://pulsar.incubator.apache.org/docs/latest/project/BinaryProtocol/
//
// The protocol definition files are part of the main Pulsar source,
// located within the Pulsar repository at:
// https://github.com/apache/pulsar/tree/master/pulsar-functions/proto/src/main/proto
//
// The generated Go code was created from the source Pulsar files at git:
//    tag:      v${plref}
//
// Files generated by the protoc-gen-go program should not be modified.
package fn
EOF


rm -rI $tmpdir
